import LenisScrollProvider from "@/providers/LenisScroll";
import "./globals.css";

import { Inter, Inconsolata } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const inconsolata = Inconsolata({
  subsets: ["latin"],
  variable: "--font-inconsolata",
});

export const metadata = {
  title: "Syncode",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${inconsolata.variable} antialiased bg-black text-white`}
      >
        <LenisScrollProvider>{children}</LenisScrollProvider>
      </body>
    </html>
  );
}
