import LenisScrollProvider from "@/providers/LenisScroll";
import "./globals.css";

import { Inter, Inconsolata } from "next/font/google";
import ReactQueryProvider from "@/providers/ReactQuery";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });
const inconsolata = Inconsolata({
  subsets: ["latin"],
  variable: "--font-inconsolata",
});

export const metadata = {
  title: "Syncode",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${inconsolata.variable} antialiased bg-black text-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position="bottom-right" />
          <ReactQueryProvider>
            <LenisScrollProvider>{children}</LenisScrollProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
